### ISSUE TITLE
KMS ARN is invalid.

### ISSUE THREAD

**Issue by DaZ3r0** [aws/aws-proton-public-roadmap#20]
Facing an issue while creating the template. 

In the **Encryption Settings section**, if we do not wish to use customized encryption settings, then it is supposed to use the default key and create the template. But here, it is not happening.

**NOTE : This occurred when I first checked and unchecked the "Customize encryption settings" checkbox. This looks like a Bug!**

![image](https://user-images.githubusercontent.com/18725276/100790696-2b0fbb00-343e-11eb-88c2-5555a129c847.png)

**If I do not check and uncheck the "Customize encryption settings" checkbox , Then it works fine!** 

![image](https://user-images.githubusercontent.com/18725276/100791176-de78af80-343e-11eb-8702-0d9854c93972.png)

**Comment by rafavallina** [comment]
Hi DaZ3r0, and thanks for submitting it! This indeed seems like a bug, so we'll have to work on it.

As this roadmap is new, we're still figuring it out what's the best way to manage bug reports like this (should we close them, or keep track of them?) so for now I'm leaving it open, but note that we've seen it and will fix it!

**Comment by nouvionp** [comment]
Just updating the thread here, but we have a fix for this that should go out on Friday. 
I will keep the issue opened until I can validate the fix in prod.

**Comment by nouvionp** [comment]
Fix was deployed to prod on 12/22/2020. Resolving this issue.
