### ISSUE TITLE
Multi-account environments

### ISSUE THREAD

**Issue by rafavallina** [aws/aws-proton-public-roadmap#3]
Enable administrators to define an AWS account per environment and have all resources in that environment and all its service instances to be created in that AWS account

**Comment by cyrildoussin** [comment]
That would amazingly useful and we’d consider switching away from another tool to do cross-account deployments if this was to happen.

**Comment by mikesir87** [comment]
I would love to see the ability to support cross-account, but also have deep integrations with AWS Organizations. Would be awesome if the templates could be defined centrally, but then shared out and discoverable across the organization. I recognize that is probably a separate feature request, but figured I'd mention it here.

**Comment by jaidisido** [comment]
Same here - I can only switch if each Proton environment is in a separate account and all are managed from the same repository

**Comment by balkat** [comment]
And seeing as the CDK team have gone a long way to developing a clever, secure self-mutating pipeline solution for multi-account scenarios it would be really great if the Proton team works closely with them to integrate it all.

**Comment by Vlaaaaaaad** [comment]
For watchers of this issue, Proton just went GA and multi-account support is here: https://aws.amazon.com/about-aws/whats-new/2021/06/aws-announces-the-general-availability-of-aws-proton/ 🎉

**Comment by rafavallina** [comment]
I was going to comment on this, but @Vlaaaaaaad did it ahead of me, thank you :)
