### ISSUE TITLE
[Request]: Proton APIs in the AWS SDKs

### ISSUE THREAD

**Issue by JohnPreston** [aws/aws-proton-public-roadmap#32]
Proton API support in boto3.
https://github.com/boto/boto3/issues/2693

**Comment by rafavallina** [comment]
@JohnPreston Thanks for the ask! Good to see some input on this. We will work on further integration with the AWS SDK, including boto3, as we move closer to GA. For the preview period we are keeping Proton isolated so that we have the possibility to make large API changes without affecting a large number of customers.

**Comment by JohnPreston** [comment]
Makes sense @rafavallina 
I was hoping to be able to integrate my project to this as AWS Proton is very much what I am aiming to do (and doing it pretty well so far for all our use-cases) and so it would be great to leverage the APIs rather than having to deal with the GUI or create all the artifacts required by Proton separately.
Any idea how long this will be in Preview?

**Comment by rafavallina** [comment]
I can't make a public commitment to when we will exit preview, I'm sorry. Know that we don't want to keep our previews too long, so hopefully it won't be too far away, but unfortunately I can't give you a specific date, I apologize.

**Comment by JohnPreston** [comment]
> I can't make a public commitment to when we will exit preview, I'm sorry. Know that we don't want to keep our previews too long, so hopefully it won't be too far away, but unfortunately I can't give you a specific date, I apologize.

No worries at all, I was not asking for any specific dates :)
I might just figure out how to generate the Proton templates for now and when comes the time make the API calls to actually create the environments etc. from that.

**Comment by mbamber** [comment]
@rafavallina - is there a preview version of the SDK that we can start to integrate with (obviously I wouldn't be expecting this to remain unchanged)

**Comment by rafavallina** [comment]
@mbamber You can add the Proton Preview model to your AWS CLI with the instructions here: https://docs.aws.amazon.com/proton/latest/userguide/getting-started-setting-up.html

**Comment by mbamber** [comment]
Thanks for the information @rafavallina - I have already played around with the CLI and am largely impressed!

Is this available in an SDK though (ideally I'm actually interested in the golang SDK, but python will suffice if necessary), rather than a CLI?

**Comment by rafavallina** [comment]
Oh sorry! I misunderstood the question. It's not available in the SDK just yet, not. We will be working on it!

**Comment by clareliguori** [comment]
Updated the title for this issue to reduce confusion around support in the different SDKs.  This issue can capture all interest in seeing Proton APIs in the AWS SDKs (all languages).  Our plan is to add Proton support into all of the official AWS SDKs and CLI at the same time.

**Comment by rafavallina** [comment]
PRoton is now live in the AWS SDK and CLI v1 with CLI v2 coming tomorrow! Check out the SDKs at https://github.com/aws
