### ISSUE TITLE
[Request]: ssm resolution separation from proton templates jinja variables

### ISSUE THREAD

**Issue by shasan101** [aws/aws-proton-public-roadmap#38]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Since the proton cfn templates are using jinja templates, the template variable declaration using jinja is similar to the cloudformation ssm resolution. When any ssm parameter is referenced in the template from the parameter store, the deployment errors out stating the cause to be the Key --for which the value was {{resolve:ssm/reference/to/parameter:1}}-- having an empty value.**

This is important for us since we use ssm to pass several values to our deployments.

**Are you currently working around this issue?**
N/A

**Additional context**
N/A

**Attachments**
N/A

**Comment by clareliguori** [comment]
Hi @shasan101, does this guidance resolve your issue?
https://github.com/aws/aws-proton-public-roadmap/issues/30#issuecomment-744688178

**Comment by shasan101** [comment]
Hi @clareliguori , thank you for the help. When I tried the suggested escaping method from the above comment, the stack was still failing. Whats working for me is:
```
Subnets:
  - '{{'{{resolve:ssm:/my/parameter/name:1}}'}}'
```
I hope this could prove useful to others as well.
