### ISSUE TITLE
Git management of templates

### ISSUE THREAD

**Issue by rafavallina** [aws/aws-proton-public-roadmap#49]
Allow platform teams to manage their template definitions using a Git repo

**Comment by gentoomaniac** [comment]
Hi!
This is something that we are currently discussing.
Can you share any information how this feature is progressing?

**Comment by rafavallina** [comment]
Hi @gentoomaniac Sorry for the late response as I was out. Apologies, can't share any specifics or timelines publicly, other than to indicate that we are in active development and feeling confident about our capacity to deliver it.

If you are looking for more details, I'd be happy to share and discuss our plans. Can you reach out to your account team to get a meeting in the books? We can ensure all the right people with their corresponding NDAs are there :)

**Comment by rafavallina** [comment]
This is live as of 11/24!

@gentoomaniac If you are still looking into it, I'd love to get your feedback. Here is the documentation: https://docs.aws.amazon.com/proton/latest/adminguide/ag-template-sync-configs.html

**Comment by gentoomaniac** [comment]
Awesome! Will look into it as soon as I can!
