### ISSUE TITLE
Unique Service Name

### ISSUE THREAD

**Issue by frgud** [aws/aws-proton-public-roadmap#53]
Hello, 

When creating a Proton service instance as part of the Create Service workflow in the AWS Console, I continually get the "unique_name required" error when supplying a service instance name.  The service instance name is unique as I have no other service instances deployed.  This blocks my ability to create a service instance.

**Comment by rafavallina** [comment]
Hi @frgud and apologies for not answering before as I messed my GitHub notifications. Have you tried reaching out to AWS support about this topic? 

I'm going to close this issue for now as this roadmap is to influence future direction of the service. Please reopen if this is a systematic issue
