### ISSUE TITLE
Service Discovery (micro service)  input in aws proton via console

### ISSUE THREAD

**Issue by hari-swrl** [aws/aws-proton-public-roadmap#56]
Can we add the service discovery end point for a micro service in console when creating service template, something similar to what's available in sample templates or will it be available in near future?

**Comment by rafavallina** [comment]
Hi @hari-swrl if I'm getting this right, this is something that you can already do, by making the endpoint available as an output in the IaC template. See here: https://github.com/aws-samples/aws-proton-sample-templates/blob/79313fb73fded293d0bd91b3a4f28aea87b93d17/loadbalanced-fargate-svc/service/instance_infrastructure/cloudformation.yaml#L305

Any outputs in the IaC template will be passed on to Proton and visible in the Proton console.

**Comment by hari-swrl** [comment]
Hi @rafavallina , thank you for the response, i understand that we will be able to configure the service endpoints in template configuration and pushing them to s3 and when creating the template providing the s3 url that will gives us the output keys ServiceEndpoint, ServiceDiscovery in output e.g,

<img width="372" alt="Screenshot 2021-06-22 at 9 19 30 AM" src="https://user-images.githubusercontent.com/81211356/122860208-f6604400-d33a-11eb-94e8-85b2446c0270.png">

But i'm interested to know if there is another process, can we be able to add these inputs in proton console directly like how we are able to give the name, description, or other properties, while creating templates via console

Thank you

**Comment by hari-swrl** [comment]
Hi  @rafavallina , After creating template through given configuration, i was able to get the service discovery option while creating a service,

Thank you

**Comment by rafavallina** [comment]
Excellent! Happy to see that it worked. Closing this issue for now
