### ISSUE TITLE
[Bug]: Template sync doesn't work for new templates

### ISSUE THREAD

**Issue by viniciuschiele** [aws/aws-proton-public-roadmap#70]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When I create a new environment template using the option `Sync templates from Git`, Proton never registers a template version 1.0.

**Are you currently working around this issue?**
After creating the template in Proton, I need to push a new commit to the template repository so that Proton registers a template version 1.0.

**Additional context**
I'm using Github to maintain my templates
I'm using the AWS Console to create the environment template

**Comment by kohidave** [comment]
Hi friend! Just a quick follow up question 🙋 

Have you synced this template in the past, then deleted it? (Or something like that)

Or is this the very first time you've tried to sync this template in your account?

**Comment by viniciuschiele** [comment]
Hi,

Yes, I have synced this template in the past and then deleted it.

Today the same thing happened to me with a service template, I've also synched this template before.

**Comment by kohidave** [comment]
Gotcha! Makes total sense. Thank you - this is a known issue. We'll work on fixing this up ASAP!

Sorry for the inconvenience!

**Comment by raresboboc** [comment]
Any updates about this? I'm still facing this issue with a github connection. With bitbucket, everything is fine.

**Comment by aws-proton-sharp-github** [comment]
Hi! If you've synced the commit to a template before, then deleted and recreated the template with the same name, we have a known issue where you'll need to make a new commit to sync the template again. 

Sorry for the inconvenience!

**Comment by piradeepk** [comment]
Hi! If you've synced the commit to a template before, then deleted and recreated the template with the same name, we have a known issue where you'll need to make a new commit to sync the template again.

Sorry for the inconvenience!
