### ISSUE TITLE
[Request]: Is Proton still actively developed?

### ISSUE THREAD

**Issue by pbn4** [aws/aws-proton-public-roadmap#77]
Hi, 

I noticed that it's been 3 years since Proton has been announced as GA and it has not been deployed to some actually quite popular AWS regions like eu-north-1. Is it because this service is no longer developed or the team is working on something else? Could you give us some insights into e.g. a plan of deploying proton to other AWS regions. I am interested in using it for an environment with 10 regions, eu-north-1 being one of them, but currently it's not possible. Maybe I misunderstood the concept from the user guide, and Proton should be run from a single region and create stacks in other regions? And this is not really a problem that it's missing in some regions?

**Comment by adamjkeller** [comment]
Hey @pbn4! Proton is actively being maintained and new features are being developed as we speak, so it is very much alive and well. For example, we recently [launched a feature called service sync](https://aws.amazon.com/blogs/containers/announcing-git-based-service-deployments-with-service-sync-for-aws-proton/), which enables developers to store their desired state of their service instance configurations in git. Last November we [announced](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-proton-available-new-regions/) six new region launches based on customer feedback but eu-north-1 was not one of them unfortunately. That said, i’ve added this region to our feature request backlog for review. 

There are ways that you can presently work around the lack of “native” region support in Proton. If you use [CodeBuild provisioning](https://docs.aws.amazon.com/proton/latest/userguide/ag-infrastructure-tmp-files-codebuild.html), the CodeBuild job that Proton manages and uses to provision environments and services will assume a role based on what the customer provides at environment creation time. This means that as long as you have the authorization set in the IAM role, you can deploy to any region. When using this setup, I would recommend making region an input value defined in the [schema](https://github.com/aws-containers/proton-codebuild-provisioning-examples/blob/main/cdk/environment-templates/cdk-vpc-ecs-cluster/v1/schema/schema.yaml) for the environment template bundle, and you can use that value when deploying resources via the IaC tool of your choice (ie, export CDK_DEFAULT_REGION=`<render-proton-input-here>`). If you make the region an environment output, the services that get deployed to this environment can determine what region to deploy to based on that output defined at the environment level (example of defining outputs at the stack level [here](https://github.com/aws-containers/proton-codebuild-provisioning-examples/blob/7c9df8068e587c7185beb7bd5d096093198fc49b/cdk/environment-templates/cdk-vpc-ecs-cluster/v1/infrastructure/lib/vpc-ecs-cluster-stack.ts#L115-L118)).

**Comment by pbn4** [comment]
Ok clear, thank you for the comprehensive response. I'll give it a try soon. :)
