### ISSUE TITLE
[BUG] Old array type input parameteres are not retained after a service instance update

### ISSUE THREAD

**Issue by davidebonavita** [aws/aws-proton-public-roadmap#78]
- Add an object array as input parameter in schema.yaml

e.g.
```
schema:
  format:
    openapi: "3.0.0"
  service_input_type: "ScheduledLambdaServiceInput"
  pipeline_input_type: "PipelineInputs"
  types:
    ScheduledLambdaServiceInput:
      type: object
      description: "Input properties for a Scheduled Lambda service."
      properties:
         lambda_environment_variables:
          type: array
          description: "List of environment variables for the Lambda function"
          items:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
```

- From the Web Console add some values to the service instance input parameter:

![image](https://github.com/aws/aws-proton-public-roadmap/assets/11682646/ff95ae01-6ae0-4605-ab32-25c0ebbfa48d)

- Deploy the changes and wait for the deployment to complete.

You can see in the deployment history the parameter values in the target spec file

- update the service instance again and add an new key value pair

![image](https://github.com/aws/aws-proton-public-roadmap/assets/11682646/6510edbf-b338-459e-b063-4b4f2011a0ba)

- Deploy the changes.

In the deployment history you will notice right away that the previous value is not retained, only the ones added during the latest update are retained. 
If you don't make any change for that input parameter and you edit some other field, all the old values are removed and an empty value for `lambda_environment_variables` will be used ("[]").

![image](https://github.com/aws/aws-proton-public-roadmap/assets/11682646/0b874480-e3fc-4cc7-a136-3c48f534235f)

**Comment by vttrmv-gamma** [comment]
Thanks David for reporting this issue, the team will be looking into it this week.

**Comment by ghost** [comment]
Thanks David for reporting this issue, the team will be looking into it this week.

**Comment by davidebonavita** [comment]
Hello @nouvionp thank you for this! I'm wondering if you're able confirm it's a bug?

Thank you again

**Comment by ghost** [comment]
Yes it's a bug, we have fix for it now, that we will deploy probably by end of next week.

**Comment by davidebonavita** [comment]
Hi @nouvionp sorry I don't know if there's a way to check if a fix has been deployed?

**Comment by ghost** [comment]
Sorry there is no way for you to check when something is fully deployed. I will mark this issue as resolved when it's done. 

We had some issues last week so started the deployment this AM and the fix is deployed to NRT but no other regions. PDX and SIN tomorrow, IAD and other regions should be the next day. Current schedule is that the deployment will be complete by EOD Thursday.

**Comment by davidebonavita** [comment]
Hi @nouvionp it seems the issue has been fixed now?

**Comment by ghost** [comment]
Yes that's correct, the fix was fully deployed, I will close this issue but please let me know or feel free to re-open this issue if you are still seeing the old behavior. Thanks!
